param(
    [Parameter(Mandatory=$true)]
    [string]$OutputFile,

    [Parameter(Mandatory=$true)]
    [string]$Version
)

$ErrorActionPreference = 'Stop'

$buildDate = Get-Date -Format 'dd.MM.yyyy'
$buildTime = Get-Date -Format 'HH:mm:ss'
$buildTimestamp = Get-Date -Format 'yyMMdd.HHmmss'
$buildVersion = "$Version.$buildTimestamp"

$content = @"
// <auto-generated/>
namespace NasreddinsCameraArcanum;

public static class BuildInfo
{
    public const string BuildDate = "$buildDate";
    public const string BuildTime = "$buildTime";
    public const string BuildVersion = "$buildVersion";
}
"@

$outputDir = Split-Path -Parent $OutputFile
if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($OutputFile, $content, $utf8NoBom)
Write-Host "BuildInfo generiert: $OutputFile (Version $buildVersion)"
